### ISSUE TITLE
Booting Zedboard ARM BIOS

### ISSUE THREAD

**Issue by r4d10n** [sergachev/litex-template#2]
I was playing around to get Zedboard ARM BIOS working, and eventually port it to Pynq Z1 board.

Running `make gateware`:

> make[1]: Leaving directory '/home/rax/exp/litex/litex-template/build/software/liblitesata'
> make[1]: Entering directory '/home/rax/exp/litex/litex-template/build/software/firmware'
>  CC       isr.o
>  CC       main.o
>  CC       firmware.elf
> riscv64-unknown-elf-gcc: error: ../libbase/crt0.o: No such file or directory
> make[1]: *** [/home/rax/exp/litex/litex-template/src/firmware/Makefile:14: firmware.elf] Error 1
> make[1]: Leaving directory '/home/rax/exp/litex/litex-template/build/software/firmware'
> Traceback (most recent call last):
>   File "/home/rax/exp/litex/litex-template/src/main.py", line 53, in <module>
>     main()
>   File "/home/rax/exp/litex/litex-template/src/main.py", line 49, in main
>     builder.build(run=args.build_gateware, synth_mode="yosys" if args.yosys else "vivado")
>   File "/home/rax/exp/litex/litex-template/lib/litex/litex/soc/integration/builder.py", line 319, in build
>     self._generate_rom_software(compile_bios=use_bios)
>   File "/home/rax/exp/litex/litex-template/lib/litex/litex/soc/integration/builder.py", line 263, in _generate_rom_software
>     subprocess.check_call(["make", "-C", dst_dir, "-f", makefile])
>   File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['make', '-C', '/home/rax/exp/litex/litex-template/build/software/firmware', '-f', '/home/rax/exp/litex/litex-template/src/firmware/Makefile']' returned non-zero exit status 2.
> Command exited with non-zero status 1
> 0:01.21
> 

I understand there has been some path changes recently from libbase to bios for crt0.o etc. Some guidance to fix this would be helpful.

**Comment by sergachev** [comment]
Tracked version of lib/litex was not up to date here - it did not include my Zynq CPU support changes in LiteX. Updated.

**Comment by r4d10n** [comment]
Thanks for the update... I tried reinitializing submodules and even a fresh pull.. Still same error.

**Comment by sergachev** [comment]
Just tried:
<add gcc-arm-none-eabi-10.3-2021.10/bin/ to PATH>
```
git clone --recursive git@github.com:sergachev/litex-template.git
cd litex-template
poetry install
poetry run python lib/litex-boards/litex_boards/targets/digilent_zedboard.py
```
<...>
```
 CC       bios.elf
chmod -x bios.elf
 OBJCOPY  bios.bin
chmod -x bios.bin
python3 -m litex.soc.software.mkmscimg bios.bin --little
python3 -m litex.soc.software.memusage bios.elf /tmp/litex-template/build/digilent_zedboard/software/bios/../include/generated/regions.ld arm-none-eabi

ROM usage: 21.07KiB 	(0.26%)
RAM usage: 0.00KiB 	(0.00%)

make: Leaving directory '/tmp/litex-template/build/digilent_zedboard/software/bios'
```

**Comment by r4d10n** [comment]
Thanks! That worked... I could bake the gateware and software just fine. Will test tomorrow on Zedboard and report back... 

Cheers!

**Comment by r4d10n** [comment]
Running `poetry run python lib/litex-boards/litex_boards/targets/digilent_zedboard.py --build --load` concludes with this:

```
Open On-Chip Debugger 0.11.0+dev-00551-gaad871805 (2022-01-14-12:35)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
zynqpl_program
Info : clock speed 1000 kHz
Info : JTAG tap: zynq_pl.bs tap/device found: 0x23727093 (mfg: 0x049 (Xilinx), part: 0x3727, ver: 0x2)
Info : JTAG tap: zynq.cpu tap/device found: 0x4ba00477 (mfg: 0x23b (ARM Ltd), part: 0xba00, ver: 0x4)
Info : zynq.cpu0: hardware has 6 breakpoints, 4 watchpoints
Info : zynq.cpu0 rev 0, partnum c09, arch f, variant 3, implementor 41
Info : zynq.cpu0: MPIDR level2 0, cluster 0, core 0, multi core, no SMT
Info : zynq.cpu1: hardware has 6 breakpoints, 4 watchpoints
Info : zynq.cpu1 rev 0, partnum c09, arch f, variant 3, implementor 41
Info : zynq.cpu1: MPIDR level2 0, cluster 0, core 1, multi core, no SMT
Info : starting gdb server for zynq.cpu0 on 3333
Info : Listening on port 3333 for gdb connections
[rax@vachas litex-template]$
```
Invoking xsct using the scripts/ps7_boot.tcl gives this:
```
[rax@vachas litex-template]$ xsct scripts/ps7_boot.tcl build/digilent_zedboard/gateware/digilent_zedboard.srcs/sources_1/ip/Zynq/ps7_init.tcl build/digilent_zedboard/software/bios/bios.elf build/digilent_zedboard/gateware/digilent_zedboard.bit
attempting to launch hw_server

****** Xilinx hw_server v2019.1
  **** Build date : May 24 2019 at 15:06:40
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

INFO: hw_server application started
INFO: Use Ctrl-C to exit hw_server application

INFO: To connect to this hw_server instance use url: TCP:127.0.0.1:3121

Already stopped
    invoked from within
"::tcf::eval -progress {apply {{msg} {puts $msg}}} {tcf_send_command tcfchan#0 RunControl suspend s e JTAG-jsn-Zed-210248707546-4ba00477-0.0}"
    (procedure "::tcf::send_command" line 4)
    invoked from within
"::tcf::send_command $chan RunControl suspend s e [list $ctx]"
    (procedure "stop" line 14)
    invoked from within
"stop"
    (file "scripts/ps7_boot.tcl" line 6)
[rax@vachas litex-template]$
```
I tried porting the Zedboard target code to Pynq Z1, using VivadoProgrammer instead of OpenOCD. Now LED Chaser is working fine here, which didn't work with Zedboard. But same output from xsct. 

How can I access the Litex ARM Bios ?

**Comment by sergachev** [comment]
I did not aim to make `--load` work yet.
xsct is the way to use this for now; find why [stop](https://github.com/sergachev/litex-template/blob/dev/scripts/ps7_boot.tcl#L6) does not work for you - try removing `stop` or running other commands in the xsct console interactively. Usual suspects are if the board is in JTAG boot mode and if clocks are fine.

**Comment by r4d10n** [comment]
Thanks !! Wit xsct in interactive mode, I could get the Led Chaser running and also access the Litex Bios from the Zedboard UART... 
```
connect
targets -set -filter {name =~ "ARM*#0"}
rst
stop
source build/digilent_zedboard/gateware/digilent_zedboard.srcs/sources_1/ip/Zynq/ps7_init.tcl 
ps7_init
ps7_post_config

dow build/digilent_zedboard/software/bios/bios.elf
con
fpga build/digilent_zedboard/gateware/digilent_zedboard.bit
```
I am unable to toggle the leds manually from the Litex Bios, and reboot command does not reload the bios.

**Comment by sergachev** [comment]
Cool.

To make CSR bus including LEDs work you need to set correct CSR_BASE in the firmware. Until @enjoy-digital gives his input on https://github.com/enjoy-digital/litex/issues/1154 you can hack it like that in digilent_zedboard.py: `self.add_constant('CSR_BASE', 0x43c0_0000)` (this will affect only firmware, not gateware).

Reboot does not work because for now xsct copies the firmware directly into DRAM. Of course proper loading from some boot media can be done too, I'll contribute this into LiteX in the next 1-2 weeks as part of general ARM boot support.

**Comment by sergachev** [comment]
Almost forgot: you will also want to swap FPGA configuration and CPU execution start in the tcl because BIOS actually needs timer0 to work properly:
```
dow build/digilent_zedboard/software/bios/bios.elf
fpga build/digilent_zedboard/gateware/digilent_zedboard.bit
con
```

**Comment by r4d10n** [comment]
Led control now works fine :) Looking forward to more generic ARM support ! 

I am trying to port this to Pynq Z1... Getting some errors during "dow" step for bios.elf. Will post it as a separate issue.

**Comment by sergachev** [comment]
> Looking forward to more generic ARM support !

I added all the required automation - try https://github.com/sergachev/litex-template/tree/main/digilent_zedboard
